/**
 * Development Agent
 * 
 * Generates source code based on implementation plan
 */

import Anthropic from "@anthropic-ai/sdk";
import { BaseAgent, AgentContext, AgentResult } from "./base";

export class DevAgent extends BaseAgent {
  private client: Anthropic;

  constructor() {
    super("DevAgent");

    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      throw new Error("ANTHROPIC_API_KEY environment variable is required");
    }

    this.client = new Anthropic({ apiKey });
  }

  async execute(context: AgentContext): Promise<AgentResult> {
    try {
      const { plan } = context as {
        plan?: {
          projectName: string;
          files: Array<{ path: string; purpose: string }>;
        };
      };

      if (!plan) {
        return {
          success: false,
          error: "Implementation plan is required",
        };
      }

      // Generate code for all files in the plan
      const generatedFiles = await this.generateCode(plan);

      return {
        success: true,
        data: {
          generatedFiles,
        },
      };
    } catch (error) {
      return this.handleError(error);
    }
  }

  private async generateCode(plan: {
    projectName: string;
    files: Array<{ path: string; purpose: string }>;
  }): Promise<
    Array<{
      path: string;
      content: string;
      language: string;
      size: number;
      createdAt: string;
    }>
  > {
    // Simplified: Generate code for key files only
    // In production, this would generate all files from plan.files
    
    const files = [
      {
        path: "package.json",
        content: JSON.stringify({
          name: plan.projectName,
          version: "1.0.0",
          type: "module",
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
          },
          dependencies: {
            next: "^15.0.0",
            react: "^19.0.0",
            "react-dom": "^19.0.0",
          },
        }, null, 2),
        language: "json",
        size: 250,
        createdAt: new Date().toISOString(),
      },
      {
        path: "README.md",
        content: `# ${plan.projectName}\n\nGenerated by Neuronix\n\n## Setup\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\``,
        language: "markdown",
        size: 100,
        createdAt: new Date().toISOString(),
      },
    ];

    return files;
  }
}
