/**
 * Integration Agent
 * 
 * Creates GitHub repositories and deploys applications
 */

import { BaseAgent, AgentContext, AgentResult } from "./base";

export class IntegrationAgent extends BaseAgent {
  constructor() {
    super("IntegrationAgent");
  }

  async execute(context: AgentContext): Promise<AgentResult> {
    try {
      const { generatedFiles, plan } = context as {
        generatedFiles?: Array<{
          path: string;
          content: string;
          language: string;
        }>;
        plan?: { projectName: string };
      };

      if (!generatedFiles || !plan) {
        return {
          success: false,
          error: "Generated files and plan are required",
        };
      }

      // Create repository (placeholder)
      const repositoryUrl = await this.createRepository(
        plan.projectName,
        generatedFiles
      );

      // Deploy to hosting (placeholder)
      const deploymentUrl = await this.deployToVercel(plan.projectName);

      return {
        success: true,
        data: {
          repositoryUrl,
          deploymentUrl,
        },
      };
    } catch (error) {
      return this.handleError(error);
    }
  }

  private async createRepository(
    projectName: string,
    files: Array<{ path: string; content: string; language: string }>
  ): Promise<string> {
    const githubToken = process.env.GITHUB_TOKEN;
    
    if (!githubToken) {
      console.warn('[IntegrationAgent] GITHUB_TOKEN not set, skipping repository creation');
      return `https://github.com/demo/${projectName}`;
    }

    try {
      // Create repository
      const createRepoResponse = await fetch('https://api.github.com/user/repos', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
        body: JSON.stringify({
          name: projectName,
          description: `Generated by Neuronix Autonomous Dev`,
          private: false,
          auto_init: true,
        }),
      });

      if (!createRepoResponse.ok) {
        const error = await createRepoResponse.text();
        console.error('[IntegrationAgent] Failed to create repository:', error);
        return `https://github.com/demo/${projectName}`;
      }

      const repo = await createRepoResponse.json();
      console.log(`[IntegrationAgent] ✅ Created repository: ${repo.html_url}`);

      // TODO: Push files to repository (requires more complex Git operations)
      // For now, just return the repository URL
      return repo.html_url;
    } catch (error) {
      console.error('[IntegrationAgent] Error creating repository:', error);
      return `https://github.com/demo/${projectName}`;
    }
  }

  private async deployToVercel(projectName: string): Promise<string> {
    const vercelToken = process.env.VERCEL_TOKEN;
    
    if (!vercelToken) {
      console.warn('[IntegrationAgent] VERCEL_TOKEN not set, skipping deployment');
      return `https://${projectName}.vercel.app`;
    }

    try {
      // Note: Vercel deployment requires more setup (linking to Git repo, etc.)
      // This is a simplified placeholder
      console.warn(`[IntegrationAgent] Vercel deployment requires manual setup`);
      return `https://${projectName}.vercel.app`;
    } catch (error) {
      console.error('[IntegrationAgent] Error deploying to Vercel:', error);
      return `https://${projectName}.vercel.app`;
    }
  }
}
